server.port=8082
spring.application.name=order-service

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/order_db
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin123}

# RabbitMQ Queue/Exchange config
rabbitmq.exchange=order.exchange
rabbitmq.queue=order.queue
rabbitmq.routing-key=order.routing.key

# Product Service URL
product.service.url=http://localhost:8081

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
